apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-kpt-functions
spec:
  workspaces:
    - name: source
      mountPath: /source
  steps:
    - name: run-kpt-functions
      image: gongpu/kpt:latest
      args:
        - fn
        - run
        - $(workspaces.source.path)/resources
        - --fn-path
        - $(workspaces.source.path)/functions.yaml
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: run-kpt-functions
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/ZhuGongpu/kpt-expanded-export-example.git"
        - name: deleteExisting
          value: "true"
    - name: kpt
      taskRef:
        name: run-kpt-functions
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-kpt-functions
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: run-kpt-functions
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace-pvc
